version: '3.3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "5001:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - api

  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./Data:/app/Data
      - ./Save:/app/Save
    environment:
      - PYTHONUNBUFFERED=1