version: '3'

services:
  http_server:
    build:
      context: .
    ports:
      - "80:80"
      - "8080:8080"
      - "8000:8000"
      - "443:443"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
    restart: always
    volumes:
      - ./Data:/app/Data


